//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPokemon
    {
        public long id { get; set; }

        [Required(ErrorMessage = "First name is required")]
        [StringLength(15, ErrorMessage = "Name can be no larger than 30 characters")]
        public string Pokemon { get; set; }

        public string Type { get; set; }
        public Nullable<int> HP { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    }
}
